from random import randint
from data_set import Operation, Data
from makespan import Solution


def generate_feasible_solution():
    """
    Generates a random feasible solution.

    :return: a random feasible solution
    """

    # this will be replaced by what Jessica and Anthony come up with
    operation_list = []
    for job in range(Data.get_number_of_jobs()):
        for task in range(Data.jobs[job].get_number_of_tasks()):
            usable_machines = Data.jobs[job].get_task(task).get_usable_machines()
            operation_list.append(Operation(task=Data.jobs[job].get_task(task),
                                            machine=usable_machines[randint(0, len(usable_machines) - 1)]))

    return Solution(operation_list)


def get_small_test_operation():
    """
    This function is only for testing purposes.
    It returns a consistent feasible solution for the smallest problem instance in the data directory.

    :return: Consistent feasible solution
    """
    # uncomment this for solution to small problem instance
    return Solution([Operation(task=Data.get_job(0).get_task(0), machine=0),
                     Operation(task=Data.get_job(0).get_task(1), machine=1),
                     Operation(task=Data.get_job(1).get_task(0), machine=1),
                     Operation(task=Data.get_job(2).get_task(0), machine=0),
                     Operation(task=Data.get_job(1).get_task(1), machine=0),
                     ])


def get_large_test_operation():

    # # uncomment this for solution to big problem instance
    return Solution([Operation(task=Data.get_job(0).get_task(0), machine=5),
                     Operation(task=Data.get_job(0).get_task(1), machine=0),
                     Operation(task=Data.get_job(0).get_task(2), machine=1),
                     Operation(task=Data.get_job(0).get_task(3), machine=2),
                     Operation(task=Data.get_job(0).get_task(4), machine=0),
                     Operation(task=Data.get_job(0).get_task(5), machine=4),
                     Operation(task=Data.get_job(0).get_task(6), machine=7),
                     Operation(task=Data.get_job(1).get_task(0), machine=6),
                     Operation(task=Data.get_job(1).get_task(1), machine=6),
                     Operation(task=Data.get_job(1).get_task(2), machine=2),
                     Operation(task=Data.get_job(1).get_task(3), machine=5),
                     Operation(task=Data.get_job(1).get_task(4), machine=2),
                     Operation(task=Data.get_job(2).get_task(0), machine=4),
                     Operation(task=Data.get_job(2).get_task(1), machine=6),
                     Operation(task=Data.get_job(2).get_task(2), machine=2),
                     Operation(task=Data.get_job(2).get_task(3), machine=3),
                     Operation(task=Data.get_job(2).get_task(4), machine=6),
                     Operation(task=Data.get_job(3).get_task(0), machine=4),
                     Operation(task=Data.get_job(3).get_task(1), machine=5),
                     Operation(task=Data.get_job(3).get_task(2), machine=0),
                     Operation(task=Data.get_job(3).get_task(3), machine=5),
                     Operation(task=Data.get_job(3).get_task(4), machine=7),
                     Operation(task=Data.get_job(3).get_task(5), machine=2),
                     Operation(task=Data.get_job(4).get_task(0), machine=1),
                     Operation(task=Data.get_job(4).get_task(1), machine=3),
                     Operation(task=Data.get_job(4).get_task(2), machine=0),
                     Operation(task=Data.get_job(4).get_task(3), machine=4),
                     Operation(task=Data.get_job(5).get_task(0), machine=4),
                     Operation(task=Data.get_job(5).get_task(1), machine=6),
                     Operation(task=Data.get_job(5).get_task(2), machine=3),
                     Operation(task=Data.get_job(5).get_task(3), machine=2),
                     Operation(task=Data.get_job(5).get_task(4), machine=5),
                     Operation(task=Data.get_job(6).get_task(0), machine=6),
                     Operation(task=Data.get_job(6).get_task(1), machine=5),
                     Operation(task=Data.get_job(6).get_task(2), machine=3),
                     Operation(task=Data.get_job(6).get_task(3), machine=5),
                     Operation(task=Data.get_job(6).get_task(4), machine=3),
                     Operation(task=Data.get_job(6).get_task(5), machine=6),
                     Operation(task=Data.get_job(7).get_task(0), machine=5),
                     Operation(task=Data.get_job(7).get_task(1), machine=0),
                     Operation(task=Data.get_job(7).get_task(2), machine=6),
                     Operation(task=Data.get_job(7).get_task(3), machine=2),
                     Operation(task=Data.get_job(8).get_task(0), machine=0),
                     Operation(task=Data.get_job(8).get_task(1), machine=2),
                     Operation(task=Data.get_job(8).get_task(2), machine=6),
                     Operation(task=Data.get_job(9).get_task(0), machine=1),
                     Operation(task=Data.get_job(9).get_task(1), machine=1),
                     Operation(task=Data.get_job(9).get_task(2), machine=2),
                     Operation(task=Data.get_job(10).get_task(0), machine=6),
                     Operation(task=Data.get_job(10).get_task(1), machine=2),
                     Operation(task=Data.get_job(10).get_task(2), machine=0),
                     Operation(task=Data.get_job(10).get_task(3), machine=2),
                     Operation(task=Data.get_job(11).get_task(0), machine=1),
                     Operation(task=Data.get_job(11).get_task(1), machine=4),
                     Operation(task=Data.get_job(11).get_task(2), machine=2),
                     Operation(task=Data.get_job(12).get_task(0), machine=4),
                     Operation(task=Data.get_job(12).get_task(1), machine=2),
                     Operation(task=Data.get_job(12).get_task(2), machine=0),
                     Operation(task=Data.get_job(12).get_task(3), machine=2),
                     Operation(task=Data.get_job(12).get_task(4), machine=1),
                     Operation(task=Data.get_job(12).get_task(5), machine=4),
                     Operation(task=Data.get_job(13).get_task(0), machine=4),
                     Operation(task=Data.get_job(13).get_task(1), machine=3),
                     Operation(task=Data.get_job(13).get_task(2), machine=2),
                     Operation(task=Data.get_job(14).get_task(0), machine=1),
                     Operation(task=Data.get_job(14).get_task(1), machine=1),
                     Operation(task=Data.get_job(14).get_task(2), machine=6),
                     Operation(task=Data.get_job(14).get_task(3), machine=6),
                     Operation(task=Data.get_job(14).get_task(4), machine=4),
                     Operation(task=Data.get_job(14).get_task(5), machine=0),
                     Operation(task=Data.get_job(14).get_task(6), machine=1),
                     Operation(task=Data.get_job(15).get_task(0), machine=5),
                     Operation(task=Data.get_job(15).get_task(1), machine=6),
                     Operation(task=Data.get_job(15).get_task(2), machine=5),
                     Operation(task=Data.get_job(15).get_task(3), machine=5),
                     Operation(task=Data.get_job(16).get_task(0), machine=4),
                     Operation(task=Data.get_job(16).get_task(1), machine=2),
                     Operation(task=Data.get_job(16).get_task(2), machine=0),
                     Operation(task=Data.get_job(17).get_task(0), machine=6),
                     Operation(task=Data.get_job(17).get_task(1), machine=7),
                     Operation(task=Data.get_job(17).get_task(2), machine=6),
                     Operation(task=Data.get_job(18).get_task(0), machine=7),
                     Operation(task=Data.get_job(18).get_task(1), machine=3),
                     Operation(task=Data.get_job(18).get_task(2), machine=0),
                     Operation(task=Data.get_job(19).get_task(0), machine=1),
                     Operation(task=Data.get_job(19).get_task(1), machine=5),
                     Operation(task=Data.get_job(19).get_task(2), machine=4),
                     Operation(task=Data.get_job(19).get_task(3), machine=5),
                     Operation(task=Data.get_job(19).get_task(4), machine=7),
                     Operation(task=Data.get_job(20).get_task(0), machine=7),
                     Operation(task=Data.get_job(20).get_task(1), machine=3),
                     Operation(task=Data.get_job(20).get_task(2), machine=7),
                     Operation(task=Data.get_job(21).get_task(0), machine=1),
                     Operation(task=Data.get_job(21).get_task(1), machine=6),
                     Operation(task=Data.get_job(21).get_task(2), machine=4),
                     Operation(task=Data.get_job(21).get_task(3), machine=0),
                     Operation(task=Data.get_job(21).get_task(4), machine=4),
                     Operation(task=Data.get_job(21).get_task(5), machine=1),
                     Operation(task=Data.get_job(22).get_task(0), machine=6),
                     Operation(task=Data.get_job(22).get_task(1), machine=4),
                     Operation(task=Data.get_job(22).get_task(2), machine=7),
                     Operation(task=Data.get_job(23).get_task(0), machine=3),
                     Operation(task=Data.get_job(23).get_task(1), machine=7),
                     Operation(task=Data.get_job(23).get_task(2), machine=7),
                     Operation(task=Data.get_job(24).get_task(0), machine=5),
                     Operation(task=Data.get_job(24).get_task(1), machine=4),
                     Operation(task=Data.get_job(24).get_task(2), machine=4),
                     Operation(task=Data.get_job(24).get_task(3), machine=1),
                     Operation(task=Data.get_job(24).get_task(4), machine=2),
                     Operation(task=Data.get_job(24).get_task(5), machine=0),
                     Operation(task=Data.get_job(24).get_task(6), machine=5),
                     Operation(task=Data.get_job(25).get_task(0), machine=4),
                     Operation(task=Data.get_job(25).get_task(1), machine=7),
                     Operation(task=Data.get_job(25).get_task(2), machine=4),
                     Operation(task=Data.get_job(25).get_task(3), machine=4),
                     Operation(task=Data.get_job(26).get_task(0), machine=4),
                     Operation(task=Data.get_job(26).get_task(1), machine=6),
                     Operation(task=Data.get_job(26).get_task(2), machine=0),
                     Operation(task=Data.get_job(26).get_task(3), machine=1),
                     Operation(task=Data.get_job(27).get_task(0), machine=1),
                     Operation(task=Data.get_job(27).get_task(1), machine=3),
                     Operation(task=Data.get_job(27).get_task(2), machine=6),
                     Operation(task=Data.get_job(28).get_task(0), machine=4),
                     Operation(task=Data.get_job(28).get_task(1), machine=1),
                     Operation(task=Data.get_job(28).get_task(2), machine=2),
                     Operation(task=Data.get_job(28).get_task(3), machine=0),
                     Operation(task=Data.get_job(28).get_task(4), machine=1),
                     Operation(task=Data.get_job(29).get_task(0), machine=4),
                     Operation(task=Data.get_job(29).get_task(1), machine=7),
                     Operation(task=Data.get_job(29).get_task(2), machine=6),
                     Operation(task=Data.get_job(29).get_task(3), machine=7),
                     Operation(task=Data.get_job(29).get_task(4), machine=4),
                     Operation(task=Data.get_job(30).get_task(0), machine=7),
                     Operation(task=Data.get_job(30).get_task(1), machine=7),
                     Operation(task=Data.get_job(30).get_task(2), machine=3),
                     Operation(task=Data.get_job(30).get_task(3), machine=6),
                     Operation(task=Data.get_job(30).get_task(4), machine=2),
                     Operation(task=Data.get_job(31).get_task(0), machine=0),
                     Operation(task=Data.get_job(31).get_task(1), machine=1),
                     Operation(task=Data.get_job(31).get_task(2), machine=3),
                     Operation(task=Data.get_job(31).get_task(3), machine=2),
                     Operation(task=Data.get_job(31).get_task(4), machine=5),
                     Operation(task=Data.get_job(31).get_task(5), machine=6),
                     Operation(task=Data.get_job(31).get_task(6), machine=2),
                     Operation(task=Data.get_job(32).get_task(0), machine=1),
                     Operation(task=Data.get_job(32).get_task(1), machine=0),
                     Operation(task=Data.get_job(32).get_task(2), machine=3),
                     Operation(task=Data.get_job(32).get_task(3), machine=5),
                     Operation(task=Data.get_job(32).get_task(4), machine=0),
                     Operation(task=Data.get_job(32).get_task(5), machine=4),
                     Operation(task=Data.get_job(33).get_task(0), machine=6),
                     Operation(task=Data.get_job(33).get_task(1), machine=3),
                     Operation(task=Data.get_job(33).get_task(2), machine=5),
                     Operation(task=Data.get_job(33).get_task(3), machine=3),
                     Operation(task=Data.get_job(33).get_task(4), machine=6),
                     Operation(task=Data.get_job(34).get_task(0), machine=7),
                     Operation(task=Data.get_job(34).get_task(1), machine=0),
                     Operation(task=Data.get_job(34).get_task(2), machine=1),
                     Operation(task=Data.get_job(34).get_task(3), machine=1),
                     Operation(task=Data.get_job(34).get_task(4), machine=4),
                     Operation(task=Data.get_job(35).get_task(0), machine=5),
                     Operation(task=Data.get_job(35).get_task(1), machine=6),
                     Operation(task=Data.get_job(35).get_task(2), machine=1),
                     Operation(task=Data.get_job(35).get_task(3), machine=5),
                     Operation(task=Data.get_job(35).get_task(4), machine=2),
                     Operation(task=Data.get_job(36).get_task(0), machine=5),
                     Operation(task=Data.get_job(36).get_task(1), machine=6),
                     Operation(task=Data.get_job(36).get_task(2), machine=5),
                     Operation(task=Data.get_job(36).get_task(3), machine=0),
                     Operation(task=Data.get_job(37).get_task(0), machine=6),
                     Operation(task=Data.get_job(37).get_task(1), machine=5),
                     Operation(task=Data.get_job(37).get_task(2), machine=5),
                     Operation(task=Data.get_job(37).get_task(3), machine=6),
                     Operation(task=Data.get_job(37).get_task(4), machine=0),
                     Operation(task=Data.get_job(37).get_task(5), machine=3),
                     Operation(task=Data.get_job(38).get_task(0), machine=0),
                     Operation(task=Data.get_job(38).get_task(1), machine=1),
                     Operation(task=Data.get_job(38).get_task(2), machine=7),
                     Operation(task=Data.get_job(39).get_task(0), machine=6),
                     Operation(task=Data.get_job(39).get_task(1), machine=7),
                     Operation(task=Data.get_job(39).get_task(2), machine=1),
                     Operation(task=Data.get_job(40).get_task(0), machine=1),
                     Operation(task=Data.get_job(40).get_task(1), machine=2),
                     Operation(task=Data.get_job(40).get_task(2), machine=5),
                     Operation(task=Data.get_job(40).get_task(3), machine=3),
                     Operation(task=Data.get_job(40).get_task(4), machine=6),
                     Operation(task=Data.get_job(41).get_task(0), machine=1),
                     Operation(task=Data.get_job(41).get_task(1), machine=5),
                     Operation(task=Data.get_job(41).get_task(2), machine=1),
                     Operation(task=Data.get_job(41).get_task(3), machine=4),
                     Operation(task=Data.get_job(41).get_task(4), machine=3),
                     Operation(task=Data.get_job(41).get_task(5), machine=3),
                     Operation(task=Data.get_job(42).get_task(0), machine=3),
                     Operation(task=Data.get_job(42).get_task(1), machine=1),
                     Operation(task=Data.get_job(42).get_task(2), machine=5),
                     Operation(task=Data.get_job(43).get_task(0), machine=6),
                     Operation(task=Data.get_job(43).get_task(1), machine=3),
                     Operation(task=Data.get_job(43).get_task(2), machine=1),
                     Operation(task=Data.get_job(44).get_task(0), machine=5),
                     Operation(task=Data.get_job(44).get_task(1), machine=3),
                     Operation(task=Data.get_job(44).get_task(2), machine=6),
                     Operation(task=Data.get_job(44).get_task(3), machine=5),
                     Operation(task=Data.get_job(44).get_task(4), machine=7),
                     Operation(task=Data.get_job(44).get_task(5), machine=6),
                     Operation(task=Data.get_job(45).get_task(0), machine=5),
                     Operation(task=Data.get_job(45).get_task(1), machine=1),
                     Operation(task=Data.get_job(45).get_task(2), machine=3),
                     Operation(task=Data.get_job(46).get_task(0), machine=4),
                     Operation(task=Data.get_job(46).get_task(1), machine=2),
                     Operation(task=Data.get_job(46).get_task(2), machine=6),
                     Operation(task=Data.get_job(47).get_task(0), machine=3),
                     Operation(task=Data.get_job(47).get_task(1), machine=7),
                     Operation(task=Data.get_job(47).get_task(2), machine=4),
                     Operation(task=Data.get_job(47).get_task(3), machine=2),
                     Operation(task=Data.get_job(48).get_task(0), machine=2),
                     Operation(task=Data.get_job(48).get_task(1), machine=7),
                     Operation(task=Data.get_job(48).get_task(2), machine=6),
                     Operation(task=Data.get_job(48).get_task(3), machine=4),
                     Operation(task=Data.get_job(48).get_task(4), machine=1),
                     Operation(task=Data.get_job(49).get_task(0), machine=2),
                     Operation(task=Data.get_job(49).get_task(1), machine=0),
                     Operation(task=Data.get_job(49).get_task(2), machine=0),
                     ])
